//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access Control Server IP.
        /// </summary>
        public static string ACSIp {
            get {
                return ResourceManager.GetString("ACSIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access control settings.
        /// </summary>
        public static string ACSSetting {
            get {
                return ResourceManager.GetString("ACSSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to update the SAM-SE with these informations ?.
        /// </summary>
        public static string AskUpdate {
            get {
                return ResourceManager.GetString("AskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing.
        /// </summary>
        public static string CAAbsent {
            get {
                return ResourceManager.GetString("CAAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string ConfFileDisabled {
            get {
                return ResourceManager.GetString("ConfFileDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification.
        /// </summary>
        public static string ConfFileDiv {
            get {
                return ResourceManager.GetString("ConfFileDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification on Random ID.
        /// </summary>
        public static string ConfFileDivRid {
            get {
                return ResourceManager.GetString("ConfFileDivRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entering SAN.
        /// </summary>
        public static string ConfigurationSAN {
            get {
                return ResourceManager.GetString("ConfigurationSAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate a CSR.
        /// </summary>
        public static string CSR {
            get {
                return ResourceManager.GetString("CSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central Unit gateway.
        /// </summary>
        public static string CUGateway {
            get {
                return ResourceManager.GetString("CUGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central Unit id.
        /// </summary>
        public static string CUId {
            get {
                return ResourceManager.GetString("CUId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central Unit IP address.
        /// </summary>
        public static string CUIp {
            get {
                return ResourceManager.GetString("CUIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central Unit mask.
        /// </summary>
        public static string CUMask {
            get {
                return ResourceManager.GetString("CUMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central Unit name.
        /// </summary>
        public static string CUName {
            get {
                return ResourceManager.GetString("CUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader current key always active.
        /// </summary>
        public static string CurrentReaderKeyActive {
            get {
                return ResourceManager.GetString("CurrentReaderKeyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Central unit settings.
        /// </summary>
        public static string CUSetting {
            get {
                return ResourceManager.GetString("CUSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default file.
        /// </summary>
        public static string DefaultFile {
            get {
                return ResourceManager.GetString("DefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will delete this intermediate certificate.
        /// </summary>
        public static string DeleteCAInt {
            get {
                return ResourceManager.GetString("DeleteCAInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will delete all the intermediates certificates.
        /// </summary>
        public static string DeleteCAIntAll {
            get {
                return ResourceManager.GetString("DeleteCAIntAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will delete this certificate.
        /// </summary>
        public static string DeleteCertificates {
            get {
                return ResourceManager.GetString("DeleteCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deletion confirmation.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete list.
        /// </summary>
        public static string DeleteList {
            get {
                return ResourceManager.GetString("DeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will delete the root authority certificate.
        /// </summary>
        public static string DeleteRCA {
            get {
                return ResourceManager.GetString("DeleteRCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire.
        /// </summary>
        public static string DESFire {
            get {
                return ResourceManager.GetString("DESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AID.
        /// </summary>
        public static string DESFireAid {
            get {
                return ResourceManager.GetString("DESFireAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AES.
        /// </summary>
        public static string DESFireCipherAes {
            get {
                return ResourceManager.GetString("DESFireCipherAes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DES/3DES.
        /// </summary>
        public static string DESFireCipherDes {
            get {
                return ResourceManager.GetString("DESFireCipherDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted.
        /// </summary>
        public static string DESFireCommunicationEncrypted {
            get {
                return ResourceManager.GetString("DESFireCommunicationEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plain.
        /// </summary>
        public static string DESFireCommunicationPlain {
            get {
                return ResourceManager.GetString("DESFireCommunicationPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology disabled.
        /// </summary>
        public static string DESFireModeDeactivated {
            get {
                return ResourceManager.GetString("DESFireModeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Private ID.
        /// </summary>
        public static string DESFireModeIdp {
            get {
                return ResourceManager.GetString("DESFireModeIdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UID.
        /// </summary>
        public static string DESFireModeUid {
            get {
                return ResourceManager.GetString("DESFireModeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag &amp; Drop files here.
        /// </summary>
        public static string DragDrop {
            get {
                return ResourceManager.GetString("DragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event viewer port.
        /// </summary>
        public static string FDLPort {
            get {
                return ResourceManager.GetString("FDLPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hardened file.
        /// </summary>
        public static string HardenedFile {
            get {
                return ResourceManager.GetString("HardenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intermediate(s) Certificate Authority(ies).
        /// </summary>
        public static string ICA {
            get {
                return ResourceManager.GetString("ICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire EV1.
        /// </summary>
        public static string JcopEv1ToolTip {
            get {
                return ResourceManager.GetString("JcopEv1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire EV3.
        /// </summary>
        public static string JcopEv3ToolTip {
            get {
                return ResourceManager.GetString("JcopEv3ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced security.
        /// </summary>
        public static string KeyEntryDESFireAdvancedSecurity {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAdvancedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication EV2.
        /// </summary>
        public static string KeyEntryDESFireAuthEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAuthEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communication.
        /// </summary>
        public static string KeyEntryDESFireCommunication {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;plain&apos; switched to &apos;encrypted&apos;.
        /// </summary>
        public static string KeyEntryDESFireCommunicationWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunicationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire Diversification.
        /// </summary>
        public static string KeyEntryDESFireDiv {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string KeyEntryDESFireDivActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AID inverted.
        /// </summary>
        public static string KeyEntryDESFireDivAid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key number included.
        /// </summary>
        public static string KeyEntryDESFireDivKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System identifier.
        /// </summary>
        public static string KeyEntryDESFireDivSi {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption.
        /// </summary>
        public static string KeyEntryDESFireEncryption {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;DES&apos; switched to &apos;AES&apos;.
        /// </summary>
        public static string KeyEntryDESFireEncryptTypeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryptTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV0.
        /// </summary>
        public static string KeyEntryDESFireEv0 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV1.
        /// </summary>
        public static string KeyEntryDESFireEv1 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV2.
        /// </summary>
        public static string KeyEntryDESFireEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV3.
        /// </summary>
        public static string KeyEntryDESFireEv3 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File number.
        /// </summary>
        public static string KeyEntryDESFireFileNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireFileNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JCOP 3.
        /// </summary>
        public static string KeyEntryDESFireJcop {
            get {
                return ResourceManager.GetString("KeyEntryDESFireJcop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JCOP 4.5.
        /// </summary>
        public static string KeyEntryDESFireJcopEv3 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireJcopEv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key number.
        /// </summary>
        public static string KeyEntryDESFireKeyNumber {
            get {
                return ResourceManager.GetString("KeyEntryDESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading mode.
        /// </summary>
        public static string KeyEntryDESFireMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MSB first.
        /// </summary>
        public static string KeyEntryDESFireMsb {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading offset.
        /// </summary>
        public static string KeyEntryDESFireOffset {
            get {
                return ResourceManager.GetString("KeyEntryDESFireOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proximity check.
        /// </summary>
        public static string KeyEntryDESFireProximityCheck {
            get {
                return ResourceManager.GetString("KeyEntryDESFireProximityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading mode.
        /// </summary>
        public static string KeyEntryDESFireReadingMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;UID&apos; switched to &apos;disabled&apos;.
        /// </summary>
        public static string KeyEntryDESFireReadingModeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire UID.
        /// </summary>
        public static string KeyEntryDESFireRid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading size.
        /// </summary>
        public static string KeyEntryDESFireSize {
            get {
                return ResourceManager.GetString("KeyEntryDESFireSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string KeyEntryDESFireUidActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KeyEntryDESFireUidIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading key number.
        /// </summary>
        public static string KeyEntryDESFireUidKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : check that the interfaces are in long format.
        /// </summary>
        public static string KeyEntryDESFireWarningSizeId {
            get {
                return ResourceManager.GetString("KeyEntryDESFireWarningSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provided SI is not of even length.
        /// </summary>
        public static string KeyEntryMessageWarningSiOdd {
            get {
                return ResourceManager.GetString("KeyEntryMessageWarningSiOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password confirmation.
        /// </summary>
        public static string KeyEntryPasswordConfirmation {
            get {
                return ResourceManager.GetString("KeyEntryPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords are not identical.
        /// </summary>
        public static string KeyEntryPasswordNotMatching {
            get {
                return ResourceManager.GetString("KeyEntryPasswordNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8 to 32 characters / 1 letter / 1 number.
        /// </summary>
        public static string KeyEntryPasswordRules {
            get {
                return ResourceManager.GetString("KeyEntryPasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Policies.
        /// </summary>
        public static string KeyEntryPolicies {
            get {
                return ResourceManager.GetString("KeyEntryPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow this object to perform DESFire authentication.
        /// </summary>
        public static string KeyEntryPoliciesAuthDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesAuthDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow decryption.
        /// </summary>
        public static string KeyEntryPoliciesDecrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow encryption.
        /// </summary>
        public static string KeyEntryPoliciesEncrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to import/export the object.
        /// </summary>
        public static string KeyEntryPoliciesImport {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to read the object.
        /// </summary>
        public static string KeyEntryPoliciesRead {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow the DESFire session key to be dumped to host.
        /// </summary>
        public static string KeyEntryPoliciesSessionKeyDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesSessionKeyDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow key wrapping.
        /// </summary>
        public static string KeyEntryPoliciesWrap {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to write the object.
        /// </summary>
        public static string KeyEntryPoliciesWrite {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE key entry type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader key.
        /// </summary>
        public static string KeyReaderK {
            get {
                return ResourceManager.GetString("KeyReaderK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating the SAM-SE lock level.
        /// </summary>
        public static string KeyStoreAutoLock {
            get {
                return ResourceManager.GetString("KeyStoreAutoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating the SAM-SE configuration file if it is not up to date.
        /// </summary>
        public static string KeyStoreAutoUpdate {
            get {
                return ResourceManager.GetString("KeyStoreAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check that the LED of the selected programming station flashes.
        /// </summary>
        public static string KeyStoreCheckStation {
            get {
                return ResourceManager.GetString("KeyStoreCheckStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection options.
        /// </summary>
        public static string KeyStoreConnexionOptions {
            get {
                return ResourceManager.GetString("KeyStoreConnexionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE default password.
        /// </summary>
        public static string KeyStoreDefaultKey {
            get {
                return ResourceManager.GetString("KeyStoreDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible to select at least one SAM-SE : Check the programming stations red lights.
        /// </summary>
        public static string KeyStoreErrorSelection {
            get {
                return ResourceManager.GetString("KeyStoreErrorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password to access SAM-SE.
        /// </summary>
        public static string KeyStorePasswordHelper {
            get {
                return ResourceManager.GetString("KeyStorePasswordHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programming Station : Mac.
        /// </summary>
        public static string KeyStoreReadersHelper {
            get {
                return ResourceManager.GetString("KeyStoreReadersHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of available SAM-SE.
        /// </summary>
        public static string KeyStoreReadersProvider {
            get {
                return ResourceManager.GetString("KeyStoreReadersProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network settings.
        /// </summary>
        public static string NetworkSetting {
            get {
                return ResourceManager.GetString("NetworkSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader new key active.
        /// </summary>
        public static string NewReaderKeyActive {
            get {
                return ResourceManager.GetString("NewReaderKeyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password for the pfx file.
        /// </summary>
        public static string PFXPassword {
            get {
                return ResourceManager.GetString("PFXPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enables protection against relay attacks.
        /// </summary>
        public static string ProximityCheckExplanation {
            get {
                return ResourceManager.GetString("ProximityCheckExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quickstart configuration interface.
        /// </summary>
        public static string QuickCommissioning {
            get {
                return ResourceManager.GetString("QuickCommissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity of RADIUS certificate.
        /// </summary>
        public static string RadiusIdentity {
            get {
                return ResourceManager.GetString("RadiusIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root Certificate Authority.
        /// </summary>
        public static string RCA {
            get {
                return ResourceManager.GetString("RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticate.
        /// </summary>
        public static string SAM_SEKeyEntryAuthenticate {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire.
        /// </summary>
        public static string SAM_SEKeyEntryDESFire {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire UID.
        /// </summary>
        public static string SAM_SEKeyEntryDESFireUid {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFireUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader.
        /// </summary>
        public static string SAM_SEKeyEntryReader {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader key personalized.
        /// </summary>
        public static string SAM_SEKeyEntryTypePerso {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryTypePerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader key Synchronic.
        /// </summary>
        public static string SAM_SEKeyEntryTypeSynchro {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryTypeSynchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save connection informations.
        /// </summary>
        public static string StoreSecret {
            get {
                return ResourceManager.GetString("StoreSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare DESFire 1 : .
        /// </summary>
        public static string ToolsConfFileConf1 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration 125kHz : .
        /// </summary>
        public static string ToolsConfFileConf125k {
            get {
                return ResourceManager.GetString("ToolsConfFileConf125k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare DESFire 2 : .
        /// </summary>
        public static string ToolsConfFileConf2 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare DESFire 3 : .
        /// </summary>
        public static string ToolsConfFileConf3 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare DESFire 4 : .
        /// </summary>
        public static string ToolsConfFileConf4 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare Classic : .
        /// </summary>
        public static string ToolsConfFileConfClassic {
            get {
                return ResourceManager.GetString("ToolsConfFileConfClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare Plus : .
        /// </summary>
        public static string ToolsConfFileConfPlus {
            get {
                return ResourceManager.GetString("ToolsConfFileConfPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration Mifare Ultralight : .
        /// </summary>
        public static string ToolsConfFileConfUltra {
            get {
                return ResourceManager.GetString("ToolsConfFileConfUltra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default file created.
        /// </summary>
        public static string ToolsConfFileDefaultOk {
            get {
                return ResourceManager.GetString("ToolsConfFileDefaultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harden file created.
        /// </summary>
        public static string ToolsConfFileHardenedOk {
            get {
                return ResourceManager.GetString("ToolsConfFileHardenedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced lock.
        /// </summary>
        public static string ToolsLockAdvancedShort {
            get {
                return ResourceManager.GetString("ToolsLockAdvancedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default lock.
        /// </summary>
        public static string ToolsLockDefaultShort {
            get {
                return ResourceManager.GetString("ToolsLockDefaultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimal lock.
        /// </summary>
        public static string ToolsLockKeyShort {
            get {
                return ResourceManager.GetString("ToolsLockKeyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock level updated.
        /// </summary>
        public static string ToolsLockLevelOk {
            get {
                return ResourceManager.GetString("ToolsLockLevelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock / Unlock.
        /// </summary>
        public static string ToolsLockUnlock {
            get {
                return ResourceManager.GetString("ToolsLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a default configuration file in SAM-SE.
        /// </summary>
        public static string ToolsSecurEvoDefault {
            get {
                return ResourceManager.GetString("ToolsSecurEvoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a harden configuration file in SAM-SE.
        /// </summary>
        public static string ToolsSecurEvoHardened {
            get {
                return ResourceManager.GetString("ToolsSecurEvoHardened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration summary :.
        /// </summary>
        public static string ToolsSummary {
            get {
                return ResourceManager.GetString("ToolsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update SAM-SE configuration file.
        /// </summary>
        public static string ToolsUpdateDefault {
            get {
                return ResourceManager.GetString("ToolsUpdateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Versions.
        /// </summary>
        public static string ToolsVersion {
            get {
                return ResourceManager.GetString("ToolsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : updating the configuration file will erase metadatas of every object.
        /// </summary>
        public static string ToolsWarningDefaultFile {
            get {
                return ResourceManager.GetString("ToolsWarningDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag&amp;Drop or browse to deposit cetificate here.
        /// </summary>
        public static string ToolTipDepositCert {
            get {
                return ResourceManager.GetString("ToolTipDepositCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are already 16 SAN. Delete some before adding a new one..
        /// </summary>
        public static string TooMuchSan {
            get {
                return ResourceManager.GetString("TooMuchSan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificates update.
        /// </summary>
        public static string UpdateCertificates {
            get {
                return ResourceManager.GetString("UpdateCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will update certificates inside the SAM-SE.
        /// </summary>
        public static string UpdateCertificatesToolTip {
            get {
                return ResourceManager.GetString("UpdateCertificatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update of SAM-SE confirmation.
        /// </summary>
        public static string UpdateConfirmation {
            get {
                return ResourceManager.GetString("UpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will update certificates inside the SAM-SE. This operation can take upto 20 seconds..
        /// </summary>
        public static string UpdateConfirmationMessage {
            get {
                return ResourceManager.GetString("UpdateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update port.
        /// </summary>
        public static string UpdatePort {
            get {
                return ResourceManager.GetString("UpdatePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version SAM-SE.
        /// </summary>
        public static string VersionSAM {
            get {
                return ResourceManager.GetString("VersionSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version CU.
        /// </summary>
        public static string VersionUGL {
            get {
                return ResourceManager.GetString("VersionUGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version PU.
        /// </summary>
        public static string VersionUT {
            get {
                return ResourceManager.GetString("VersionUT", resourceCulture);
            }
        }
    }
}
