//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ConfFileDisabled {
            get {
                return ResourceManager.GetString("ConfFileDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversification.
        /// </summary>
        public static string ConfFileDiv {
            get {
                return ResourceManager.GetString("ConfFileDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversification on Random ID.
        /// </summary>
        public static string ConfFileDivRid {
            get {
                return ResourceManager.GetString("ConfFileDivRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire.
        /// </summary>
        public static string DESFire {
            get {
                return ResourceManager.GetString("DESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID.
        /// </summary>
        public static string DESFireAid {
            get {
                return ResourceManager.GetString("DESFireAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES.
        /// </summary>
        public static string DESFireCipherAes {
            get {
                return ResourceManager.GetString("DESFireCipherAes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES/3DES.
        /// </summary>
        public static string DESFireCipherDes {
            get {
                return ResourceManager.GetString("DESFireCipherDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string DESFireCommunicationEncrypted {
            get {
                return ResourceManager.GetString("DESFireCommunicationEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string DESFireCommunicationPlain {
            get {
                return ResourceManager.GetString("DESFireCommunicationPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology disabled.
        /// </summary>
        public static string DESFireModeDeactivated {
            get {
                return ResourceManager.GetString("DESFireModeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private ID.
        /// </summary>
        public static string DESFireModeIdp {
            get {
                return ResourceManager.GetString("DESFireModeIdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string DESFireModeUid {
            get {
                return ResourceManager.GetString("DESFireModeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced security.
        /// </summary>
        public static string KeyEntryDESFireAdvancedSecurity {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAdvancedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication EV2.
        /// </summary>
        public static string KeyEntryDESFireAuthEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAuthEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string KeyEntryDESFireCommunication {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : &apos;plain&apos; switched to &apos;encrypted&apos;.
        /// </summary>
        public static string KeyEntryDESFireCommunicationWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunicationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire Diversification.
        /// </summary>
        public static string KeyEntryDESFireDiv {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string KeyEntryDESFireDivActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID Inverted.
        /// </summary>
        public static string KeyEntryDESFireDivAid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key n° included.
        /// </summary>
        public static string KeyEntryDESFireDivKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Identifier.
        /// </summary>
        public static string KeyEntryDESFireDivSi {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string KeyEntryDESFireEncryption {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : &apos;DES&apos; switched to &apos;AES&apos;.
        /// </summary>
        public static string KeyEntryDESFireEncryptTypeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryptTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0.
        /// </summary>
        public static string KeyEntryDESFireEv0 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV1.
        /// </summary>
        public static string KeyEntryDESFireEv1 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV2.
        /// </summary>
        public static string KeyEntryDESFireEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV3.
        /// </summary>
        public static string KeyEntryDESFireEv3 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File number.
        /// </summary>
        public static string KeyEntryDESFireFileNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireFileNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCOP.
        /// </summary>
        public static string KeyEntryDESFireJcop {
            get {
                return ResourceManager.GetString("KeyEntryDESFireJcop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key number.
        /// </summary>
        public static string KeyEntryDESFireKeyNumber {
            get {
                return ResourceManager.GetString("KeyEntryDESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading mode.
        /// </summary>
        public static string KeyEntryDESFireMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSB first.
        /// </summary>
        public static string KeyEntryDESFireMsb {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading offset.
        /// </summary>
        public static string KeyEntryDESFireOffset {
            get {
                return ResourceManager.GetString("KeyEntryDESFireOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity Check.
        /// </summary>
        public static string KeyEntryDESFireProximityCheck {
            get {
                return ResourceManager.GetString("KeyEntryDESFireProximityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading mode.
        /// </summary>
        public static string KeyEntryDESFireReadingMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : &apos;UID&apos; switched to &apos;disabled&apos;.
        /// </summary>
        public static string KeyEntryDESFireReadingModeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire UID.
        /// </summary>
        public static string KeyEntryDESFireRid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading size.
        /// </summary>
        public static string KeyEntryDESFireSize {
            get {
                return ResourceManager.GetString("KeyEntryDESFireSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string KeyEntryDESFireUidActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string KeyEntryDESFireUidIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Key Number.
        /// </summary>
        public static string KeyEntryDESFireUidKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : check that the interfaces are in long format.
        /// </summary>
        public static string KeyEntryDESFireWarningSizeId {
            get {
                return ResourceManager.GetString("KeyEntryDESFireWarningSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided SI is not of even length.
        /// </summary>
        public static string KeyEntryMessageWarningSiOdd {
            get {
                return ResourceManager.GetString("KeyEntryMessageWarningSiOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        public static string KeyEntryPasswordConfirmation {
            get {
                return ResourceManager.GetString("KeyEntryPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not identical.
        /// </summary>
        public static string KeyEntryPasswordNotMatching {
            get {
                return ResourceManager.GetString("KeyEntryPasswordNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 to 32 characters / 1 letter / 1 number.
        /// </summary>
        public static string KeyEntryPasswordRules {
            get {
                return ResourceManager.GetString("KeyEntryPasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string KeyEntryPolicies {
            get {
                return ResourceManager.GetString("KeyEntryPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow this object to perform DESFire Authentication.
        /// </summary>
        public static string KeyEntryPoliciesAuthDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesAuthDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow decryption.
        /// </summary>
        public static string KeyEntryPoliciesDecrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow encryption.
        /// </summary>
        public static string KeyEntryPoliciesEncrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to import/export the object.
        /// </summary>
        public static string KeyEntryPoliciesImport {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to read the object.
        /// </summary>
        public static string KeyEntryPoliciesRead {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the DESFire session key to be dumped to host.
        /// </summary>
        public static string KeyEntryPoliciesSessionKeyDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesSessionKeyDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow key wrapping.
        /// </summary>
        public static string KeyEntryPoliciesWrap {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to write the object.
        /// </summary>
        public static string KeyEntryPoliciesWrite {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM-SE Key Entry Type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM-SE default key.
        /// </summary>
        public static string KeyStoreDefaultKey {
            get {
                return ResourceManager.GetString("KeyStoreDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to select at least one SAM-SE : Check the programming stations red lights.
        /// </summary>
        public static string KeyStoreErrorSelection {
            get {
                return ResourceManager.GetString("KeyStoreErrorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to access SAM-SE.
        /// </summary>
        public static string KeyStorePasswordHelper {
            get {
                return ResourceManager.GetString("KeyStorePasswordHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM-SE		MAC		Version.
        /// </summary>
        public static string KeyStoreReadersHelper {
            get {
                return ResourceManager.GetString("KeyStoreReadersHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available SAM-SE.
        /// </summary>
        public static string KeyStoreReadersProvider {
            get {
                return ResourceManager.GetString("KeyStoreReadersProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string SAM_SEKeyEntryAuthenticate {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire.
        /// </summary>
        public static string SAM_SEKeyEntryDESFire {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire UID.
        /// </summary>
        public static string SAM_SEKeyEntryDESFireUid {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFireUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration 1 : .
        /// </summary>
        public static string ToolsConfFileConf1 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration 2 : .
        /// </summary>
        public static string ToolsConfFileConf2 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration 3 : .
        /// </summary>
        public static string ToolsConfFileConf3 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration 4 : .
        /// </summary>
        public static string ToolsConfFileConf4 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default file created.
        /// </summary>
        public static string ToolsConfFileDefaultOk {
            get {
                return ResourceManager.GetString("ToolsConfFileDefaultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced lock.
        /// </summary>
        public static string ToolsLockAdvancedShort {
            get {
                return ResourceManager.GetString("ToolsLockAdvancedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default lock.
        /// </summary>
        public static string ToolsLockDefaultShort {
            get {
                return ResourceManager.GetString("ToolsLockDefaultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal lock.
        /// </summary>
        public static string ToolsLockKeyShort {
            get {
                return ResourceManager.GetString("ToolsLockKeyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock level updated.
        /// </summary>
        public static string ToolsLockLevelOk {
            get {
                return ResourceManager.GetString("ToolsLockLevelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock / Unlock.
        /// </summary>
        public static string ToolsLockUnlock {
            get {
                return ResourceManager.GetString("ToolsLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a default configuration file in SAM-SE.
        /// </summary>
        public static string ToolsSecurEvoDefault {
            get {
                return ResourceManager.GetString("ToolsSecurEvoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary :.
        /// </summary>
        public static string ToolsSummary {
            get {
                return ResourceManager.GetString("ToolsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SAM-SE with default values.
        /// </summary>
        public static string ToolsUpdateDefault {
            get {
                return ResourceManager.GetString("ToolsUpdateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : updating the configuration file to default values will erase metadatas of every object.
        /// </summary>
        public static string ToolsWarningDefaultFile {
            get {
                return ResourceManager.GetString("ToolsWarningDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
