//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.SAM_SE.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string ConfFileDisabled {
            get {
                return ResourceManager.GetString("ConfFileDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification.
        /// </summary>
        public static string ConfFileDiv {
            get {
                return ResourceManager.GetString("ConfFileDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification on Random ID.
        /// </summary>
        public static string ConfFileDivRid {
            get {
                return ResourceManager.GetString("ConfFileDivRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire.
        /// </summary>
        public static string DESFire {
            get {
                return ResourceManager.GetString("DESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AID.
        /// </summary>
        public static string DESFireAid {
            get {
                return ResourceManager.GetString("DESFireAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AES.
        /// </summary>
        public static string DESFireCipherAes {
            get {
                return ResourceManager.GetString("DESFireCipherAes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DES/3DES.
        /// </summary>
        public static string DESFireCipherDes {
            get {
                return ResourceManager.GetString("DESFireCipherDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted.
        /// </summary>
        public static string DESFireCommunicationEncrypted {
            get {
                return ResourceManager.GetString("DESFireCommunicationEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plain.
        /// </summary>
        public static string DESFireCommunicationPlain {
            get {
                return ResourceManager.GetString("DESFireCommunicationPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology disabled.
        /// </summary>
        public static string DESFireModeDeactivated {
            get {
                return ResourceManager.GetString("DESFireModeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Private ID.
        /// </summary>
        public static string DESFireModeIdp {
            get {
                return ResourceManager.GetString("DESFireModeIdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UID.
        /// </summary>
        public static string DESFireModeUid {
            get {
                return ResourceManager.GetString("DESFireModeUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire EV1.
        /// </summary>
        public static string JcopEv1ToolTip {
            get {
                return ResourceManager.GetString("JcopEv1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire EV3.
        /// </summary>
        public static string JcopEv3ToolTip {
            get {
                return ResourceManager.GetString("JcopEv3ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced security.
        /// </summary>
        public static string KeyEntryDESFireAdvancedSecurity {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAdvancedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication EV2.
        /// </summary>
        public static string KeyEntryDESFireAuthEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireAuthEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communication.
        /// </summary>
        public static string KeyEntryDESFireCommunication {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;plain&apos; switched to &apos;encrypted&apos;.
        /// </summary>
        public static string KeyEntryDESFireCommunicationWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireCommunicationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire Diversification.
        /// </summary>
        public static string KeyEntryDESFireDiv {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string KeyEntryDESFireDivActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AID inverted.
        /// </summary>
        public static string KeyEntryDESFireDivAid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key number included.
        /// </summary>
        public static string KeyEntryDESFireDivKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System identifier.
        /// </summary>
        public static string KeyEntryDESFireDivSi {
            get {
                return ResourceManager.GetString("KeyEntryDESFireDivSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption.
        /// </summary>
        public static string KeyEntryDESFireEncryption {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;DES&apos; switched to &apos;AES&apos;.
        /// </summary>
        public static string KeyEntryDESFireEncryptTypeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEncryptTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV0.
        /// </summary>
        public static string KeyEntryDESFireEv0 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV1.
        /// </summary>
        public static string KeyEntryDESFireEv1 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV2.
        /// </summary>
        public static string KeyEntryDESFireEv2 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EV3.
        /// </summary>
        public static string KeyEntryDESFireEv3 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireEv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File number.
        /// </summary>
        public static string KeyEntryDESFireFileNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireFileNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JCOP 3.
        /// </summary>
        public static string KeyEntryDESFireJcop {
            get {
                return ResourceManager.GetString("KeyEntryDESFireJcop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JCOP 4.5.
        /// </summary>
        public static string KeyEntryDESFireJcopEv3 {
            get {
                return ResourceManager.GetString("KeyEntryDESFireJcopEv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key number.
        /// </summary>
        public static string KeyEntryDESFireKeyNumber {
            get {
                return ResourceManager.GetString("KeyEntryDESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading mode.
        /// </summary>
        public static string KeyEntryDESFireMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MSB first.
        /// </summary>
        public static string KeyEntryDESFireMsb {
            get {
                return ResourceManager.GetString("KeyEntryDESFireMsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading offset.
        /// </summary>
        public static string KeyEntryDESFireOffset {
            get {
                return ResourceManager.GetString("KeyEntryDESFireOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proximity check.
        /// </summary>
        public static string KeyEntryDESFireProximityCheck {
            get {
                return ResourceManager.GetString("KeyEntryDESFireProximityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading mode.
        /// </summary>
        public static string KeyEntryDESFireReadingMode {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : &apos;UID&apos; switched to &apos;disabled&apos;.
        /// </summary>
        public static string KeyEntryDESFireReadingModeWarning {
            get {
                return ResourceManager.GetString("KeyEntryDESFireReadingModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire UID.
        /// </summary>
        public static string KeyEntryDESFireRid {
            get {
                return ResourceManager.GetString("KeyEntryDESFireRid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading size.
        /// </summary>
        public static string KeyEntryDESFireSize {
            get {
                return ResourceManager.GetString("KeyEntryDESFireSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string KeyEntryDESFireUidActive {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KeyEntryDESFireUidIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading key number.
        /// </summary>
        public static string KeyEntryDESFireUidKeyNum {
            get {
                return ResourceManager.GetString("KeyEntryDESFireUidKeyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : check that the interfaces are in long format.
        /// </summary>
        public static string KeyEntryDESFireWarningSizeId {
            get {
                return ResourceManager.GetString("KeyEntryDESFireWarningSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provided SI is not of even length.
        /// </summary>
        public static string KeyEntryMessageWarningSiOdd {
            get {
                return ResourceManager.GetString("KeyEntryMessageWarningSiOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password confirmation.
        /// </summary>
        public static string KeyEntryPasswordConfirmation {
            get {
                return ResourceManager.GetString("KeyEntryPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords are not identical.
        /// </summary>
        public static string KeyEntryPasswordNotMatching {
            get {
                return ResourceManager.GetString("KeyEntryPasswordNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8 to 32 characters / 1 letter / 1 number.
        /// </summary>
        public static string KeyEntryPasswordRules {
            get {
                return ResourceManager.GetString("KeyEntryPasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Policies.
        /// </summary>
        public static string KeyEntryPolicies {
            get {
                return ResourceManager.GetString("KeyEntryPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow this object to perform DESFire authentication.
        /// </summary>
        public static string KeyEntryPoliciesAuthDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesAuthDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow decryption.
        /// </summary>
        public static string KeyEntryPoliciesDecrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow encryption.
        /// </summary>
        public static string KeyEntryPoliciesEncrypt {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to import/export the object.
        /// </summary>
        public static string KeyEntryPoliciesImport {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to read the object.
        /// </summary>
        public static string KeyEntryPoliciesRead {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow the DESFire session key to be dumped to host.
        /// </summary>
        public static string KeyEntryPoliciesSessionKeyDESFire {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesSessionKeyDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow key wrapping.
        /// </summary>
        public static string KeyEntryPoliciesWrap {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow to write the object.
        /// </summary>
        public static string KeyEntryPoliciesWrite {
            get {
                return ResourceManager.GetString("KeyEntryPoliciesWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE key entry type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating the SAM-SE lock level.
        /// </summary>
        public static string KeyStoreAutoLock {
            get {
                return ResourceManager.GetString("KeyStoreAutoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updating the SAM-SE configuration file if it is not up to date.
        /// </summary>
        public static string KeyStoreAutoUpdate {
            get {
                return ResourceManager.GetString("KeyStoreAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check that the LED of the selected programming station flashes.
        /// </summary>
        public static string KeyStoreCheckStation {
            get {
                return ResourceManager.GetString("KeyStoreCheckStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection options.
        /// </summary>
        public static string KeyStoreConnexionOptions {
            get {
                return ResourceManager.GetString("KeyStoreConnexionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE default key.
        /// </summary>
        public static string KeyStoreDefaultKey {
            get {
                return ResourceManager.GetString("KeyStoreDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible to select at least one SAM-SE : Check the programming stations red lights.
        /// </summary>
        public static string KeyStoreErrorSelection {
            get {
                return ResourceManager.GetString("KeyStoreErrorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password to access SAM-SE.
        /// </summary>
        public static string KeyStorePasswordHelper {
            get {
                return ResourceManager.GetString("KeyStorePasswordHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programming Station : Type - Mac - Version.
        /// </summary>
        public static string KeyStoreReadersHelper {
            get {
                return ResourceManager.GetString("KeyStoreReadersHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of available SAM-SE.
        /// </summary>
        public static string KeyStoreReadersProvider {
            get {
                return ResourceManager.GetString("KeyStoreReadersProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enables protection against relay attacks.
        /// </summary>
        public static string ProximityCheckExplanation {
            get {
                return ResourceManager.GetString("ProximityCheckExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticate.
        /// </summary>
        public static string SAM_SEKeyEntryAuthenticate {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire.
        /// </summary>
        public static string SAM_SEKeyEntryDESFire {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire UID.
        /// </summary>
        public static string SAM_SEKeyEntryDESFireUid {
            get {
                return ResourceManager.GetString("SAM_SEKeyEntryDESFireUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save connection informations.
        /// </summary>
        public static string StoreSecret {
            get {
                return ResourceManager.GetString("StoreSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration 1 : .
        /// </summary>
        public static string ToolsConfFileConf1 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration 2 : .
        /// </summary>
        public static string ToolsConfFileConf2 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration 3 : .
        /// </summary>
        public static string ToolsConfFileConf3 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration 4 : .
        /// </summary>
        public static string ToolsConfFileConf4 {
            get {
                return ResourceManager.GetString("ToolsConfFileConf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default file created.
        /// </summary>
        public static string ToolsConfFileDefaultOk {
            get {
                return ResourceManager.GetString("ToolsConfFileDefaultOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced lock.
        /// </summary>
        public static string ToolsLockAdvancedShort {
            get {
                return ResourceManager.GetString("ToolsLockAdvancedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default lock.
        /// </summary>
        public static string ToolsLockDefaultShort {
            get {
                return ResourceManager.GetString("ToolsLockDefaultShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimal lock.
        /// </summary>
        public static string ToolsLockKeyShort {
            get {
                return ResourceManager.GetString("ToolsLockKeyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock level updated.
        /// </summary>
        public static string ToolsLockLevelOk {
            get {
                return ResourceManager.GetString("ToolsLockLevelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock / Unlock.
        /// </summary>
        public static string ToolsLockUnlock {
            get {
                return ResourceManager.GetString("ToolsLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a default configuration file in SAM-SE.
        /// </summary>
        public static string ToolsSecurEvoDefault {
            get {
                return ResourceManager.GetString("ToolsSecurEvoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary :.
        /// </summary>
        public static string ToolsSummary {
            get {
                return ResourceManager.GetString("ToolsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update SAM-SE with default values.
        /// </summary>
        public static string ToolsUpdateDefault {
            get {
                return ResourceManager.GetString("ToolsUpdateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : updating the configuration file to default values will erase metadatas of every object.
        /// </summary>
        public static string ToolsWarningDefaultFile {
            get {
                return ResourceManager.GetString("ToolsWarningDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
