//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.Wizard.SAMAccessControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.Wizard.SAMAccessControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID.
        /// </summary>
        public static string DESFireAID {
            get {
                return ResourceManager.GetString("DESFireAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DESFire Application Identifier.
        /// </summary>
        public static string DESFireAIDHelper {
            get {
                return ResourceManager.GetString("DESFireAIDHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Number.
        /// </summary>
        public static string DESFireKeyNumber {
            get {
                return ResourceManager.GetString("DESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DESFire Key Number.
        /// </summary>
        public static string DESFireKeyNumberHelper {
            get {
                return ResourceManager.GetString("DESFireKeyNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM for Access Control.
        /// </summary>
        public static string FactoryName {
            get {
                return ResourceManager.GetString("FactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new SAM Master Key.
        /// </summary>
        public static string GenerateSAMMasterKey {
            get {
                return ResourceManager.GetString("GenerateSAMMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new SAM Unlock Key.
        /// </summary>
        public static string GenerateSAMUnlockKey {
            get {
                return ResourceManager.GetString("GenerateSAMUnlockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC Key.
        /// </summary>
        public static string PICCKey {
            get {
                return ResourceManager.GetString("PICCKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define SAM key entries following recommended guidelines for a SAM used by Access Control systems..
        /// </summary>
        public static string WizardDescription {
            get {
                return ResourceManager.GetString("WizardDescription", resourceCulture);
            }
        }
    }
}
