//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyManager.Library.KeyStore.KeePass.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyManager.Library.KeyStore.KeePass.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Ready to connect • No profile selected.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Exploring....
        /// </summary>
        public static string AvailabilityProcessing {
            get {
                return ResourceManager.GetString("AvailabilityProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed : {0}.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ➤.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Password or a master key file required.
        /// </summary>
        public static string CreateCredentialRequired {
            get {
                return ResourceManager.GetString("CreateCredentialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ File already exists.
        /// </summary>
        public static string CreateFileExists {
            get {
                return ResourceManager.GetString("CreateFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ File path is required.
        /// </summary>
        public static string CreateFileNotFound {
            get {
                return ResourceManager.GetString("CreateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Keystore created successfully.
        /// </summary>
        public static string CreateSuccessful {
            get {
                return ResourceManager.GetString("CreateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating keystore....
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Mode.
        /// </summary>
        public static string CredentialMode {
            get {
                return ResourceManager.GetString("CredentialMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Failed to close database : {0}.
        /// </summary>
        public static string DatabaseCloseFailed {
            get {
                return ResourceManager.GetString("DatabaseCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path missing.
        /// </summary>
        public static string DatabasePathMissing {
            get {
                return ResourceManager.GetString("DatabasePathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ KeePass database validated successfully ! • {0}.
        /// </summary>
        public static string DatabaseValidated {
            get {
                return ResourceManager.GetString("DatabaseValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate the newly created database : {0}.
        /// </summary>
        public static string DatabaseValidatedFailed {
            get {
                return ResourceManager.GetString("DatabaseValidatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Root).
        /// </summary>
        public static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Root).
        /// </summary>
        public static string DefaultProfileName {
            get {
                return ResourceManager.GetString("DefaultProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Error : {0}.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a KeePass database file..
        /// </summary>
        public static string ErrorFile {
            get {
                return ResourceManager.GetString("ErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected KeePass file does not exist..
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password or key file is missing or incorrect..
        /// </summary>
        public static string ErrorFilePwdNotFound {
            get {
                return ResourceManager.GetString("ErrorFilePwdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Profiles.
        /// </summary>
        public static string Exhaustive {
            get {
                return ResourceManager.GetString("Exhaustive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass File (.kdbx).
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ KeePass file selected : {0}.
        /// </summary>
        public static string FileSelected {
            get {
                return ResourceManager.GetString("FileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass Database (*.kdbx)|*.kdbx|All Files (*.*)|*.*.
        /// </summary>
        public static string KeePassDbFilter {
            get {
                return ResourceManager.GetString("KeePassDbFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key File (*.keyx)|*.keyx|All Files (*.*)|*.*.
        /// </summary>
        public static string KeyFileFilter {
            get {
                return ResourceManager.GetString("KeyFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file only.
        /// </summary>
        public static string KeyFileOnly {
            get {
                return ResourceManager.GetString("KeyFileOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔑 Key file selected : {0}.
        /// </summary>
        public static string KeyFileSelected {
            get {
                return ResourceManager.GetString("KeyFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master key 🔑.
        /// </summary>
        public static string MasterKey {
            get {
                return ResourceManager.GetString("MasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master key file is required.
        /// </summary>
        public static string MasterKeyRequired {
            get {
                return ResourceManager.GetString("MasterKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password 🔐.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password only.
        /// </summary>
        public static string PasswordOnly {
            get {
                return ResourceManager.GetString("PasswordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password + Key.
        /// </summary>
        public static string PasswordPlusKey {
            get {
                return ResourceManager.GetString("PasswordPlusKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile :.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔗 Profile Explorer.
        /// </summary>
        public static string ProfileChecker {
            get {
                return ResourceManager.GetString("ProfileChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass Database (.kdbx).
        /// </summary>
        public static string SelectKeePassDatabase {
            get {
                return ResourceManager.GetString("SelectKeePassDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Master Key.
        /// </summary>
        public static string SelectMasterKey {
            get {
                return ResourceManager.GetString("SelectMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Keys.
        /// </summary>
        public static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePass Database Connection.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
