//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.HSM_PKCS11.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.HSM_PKCS11.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive.
        /// </summary>
        public static string Derive {
            get {
                return ResourceManager.GetString("Derive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce Label use.
        /// </summary>
        public static string EnforceLabelUse {
            get {
                return ResourceManager.GetString("EnforceLabelUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractable.
        /// </summary>
        public static string Extractable {
            get {
                return ResourceManager.GetString("Extractable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKCS#11 Library.
        /// </summary>
        public static string LibraryPath {
            get {
                return ResourceManager.GetString("LibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKCS#11 Library path.
        /// </summary>
        public static string LibraryPathHelper {
            get {
                return ResourceManager.GetString("LibraryPathHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitive.
        /// </summary>
        public static string Sensitive {
            get {
                return ResourceManager.GetString("Sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Value.
        /// </summary>
        public static string SlotFilter {
            get {
                return ResourceManager.GetString("SlotFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter value.
        /// </summary>
        public static string SlotFilterHelper {
            get {
                return ResourceManager.GetString("SlotFilterHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Filter.
        /// </summary>
        public static string SlotFilterType {
            get {
                return ResourceManager.GetString("SlotFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for slot selection.
        /// </summary>
        public static string SlotFilterTypeHelper {
            get {
                return ResourceManager.GetString("SlotFilterTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StoreSecret {
            get {
                return ResourceManager.GetString("StoreSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user to authenticate with.
        /// </summary>
        public static string UserHelper {
            get {
                return ResourceManager.GetString("UserHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string UserPIN {
            get {
                return ResourceManager.GetString("UserPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user PIN.
        /// </summary>
        public static string UserPINHelper {
            get {
                return ResourceManager.GetString("UserPINHelper", resourceCulture);
            }
        }
    }
}
