//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.SAM_SE.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.SAM_SE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The AID can&apos;t store this value.
        /// </summary>
        public static string AidNotValid {
            get {
                return ResourceManager.GetString("AidNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The AID is not filled in.
        /// </summary>
        public static string AidWarningMissing {
            get {
                return ResourceManager.GetString("AidWarningMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The AID is not equal to length 6.
        /// </summary>
        public static string AidWarningWrongLength {
            get {
                return ResourceManager.GetString("AidWarningWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The favourite SAM-SE is not connected.
        /// </summary>
        public static string FavoriteSAM_SEDisconnected {
            get {
                return ResourceManager.GetString("FavoriteSAM_SEDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This type of key entry is not supported.
        /// </summary>
        public static string KeyStoreEntryNotSupported {
            get {
                return ResourceManager.GetString("KeyStoreEntryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key entry do not exists.
        /// </summary>
        public static string KeyStoreKeyEntryMissing {
            get {
                return ResourceManager.GetString("KeyStoreKeyEntryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key entry type do not exists.
        /// </summary>
        public static string KeyStoreKeyEntryTypeMissing {
            get {
                return ResourceManager.GetString("KeyStoreKeyEntryTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password is not valid.
        /// </summary>
        public static string KeyStorePasswordInvalid {
            get {
                return ResourceManager.GetString("KeyStorePasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The two passwords are not matching.
        /// </summary>
        public static string KeyStorePasswordNotMatching {
            get {
                return ResourceManager.GetString("KeyStorePasswordNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing SAM-SE key store properties.
        /// </summary>
        public static string KeyStorePropertiesMissing {
            get {
                return ResourceManager.GetString("KeyStorePropertiesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key value.
        /// </summary>
        public static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIFARE DESFire key : biometric configuration.
        /// </summary>
        public static string LabelBioa {
            get {
                return ResourceManager.GetString("LabelBioa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIFARE DESFire key : configuration.
        /// </summary>
        public static string LabelDfxa {
            get {
                return ResourceManager.GetString("LabelDfxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE authentication key.
        /// </summary>
        public static string LabelScp3 {
            get {
                return ResourceManager.GetString("LabelScp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random UID key : configuration.
        /// </summary>
        public static string LabelUidx {
            get {
                return ResourceManager.GetString("LabelUidx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown object.
        /// </summary>
        public static string LabelUnknown {
            get {
                return ResourceManager.GetString("LabelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default lock : keys and files are locked inside UTPs.
        /// </summary>
        public static string LockDefault {
            get {
                return ResourceManager.GetString("LockDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimal lock : only the secrets keys are locked.
        /// </summary>
        public static string LockKey {
            get {
                return ResourceManager.GetString("LockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced lock : keys and files are locked inside UTPs and readonly by Synchronic softwares.
        /// </summary>
        public static string LockReadOnly {
            get {
                return ResourceManager.GetString("LockReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password do not contains a digit.
        /// </summary>
        public static string PasswordErrorDigit {
            get {
                return ResourceManager.GetString("PasswordErrorDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password do not contains at least 8 characters.
        /// </summary>
        public static string PasswordErrorLength {
            get {
                return ResourceManager.GetString("PasswordErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password do not contains a letter.
        /// </summary>
        public static string PasswordErrorLetter {
            get {
                return ResourceManager.GetString("PasswordErrorLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No programming station is selected.
        /// </summary>
        public static string ProgrammingStationMissing {
            get {
                return ResourceManager.GetString("ProgrammingStationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communication with SAM-SE is disturbed.
        /// </summary>
        public static string SAM_SEErrorBadConditions {
            get {
                return ResourceManager.GetString("SAM_SEErrorBadConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE action done.
        /// </summary>
        public static string SAM_SEErrorDone {
            get {
                return ResourceManager.GetString("SAM_SEErrorDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No SAM-SE is connected.
        /// </summary>
        public static string SAM_SEErrorNoSAM_SE {
            get {
                return ResourceManager.GetString("SAM_SEErrorNoSAM_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version of configuration file is not up to date.
        /// </summary>
        public static string SAM_SEErrorOldVersion {
            get {
                return ResourceManager.GetString("SAM_SEErrorOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE generic error, a &apos;get_last_error&apos; should have been called.
        /// </summary>
        public static string SAM_SEErrorOnError {
            get {
                return ResourceManager.GetString("SAM_SEErrorOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected programming station seems disconnected.
        /// </summary>
        public static string SAM_SEErrorProbablyDisconnected {
            get {
                return ResourceManager.GetString("SAM_SEErrorProbablyDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE function was incorrectly called.
        /// </summary>
        public static string SAM_SEErrorWrongArg {
            get {
                return ResourceManager.GetString("SAM_SEErrorWrongArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE index do not exists.
        /// </summary>
        public static string SAM_SEErrorWrongIndex {
            get {
                return ResourceManager.GetString("SAM_SEErrorWrongIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE context is corrupted.
        /// </summary>
        public static string SAM_SEErrorWrongPtr {
            get {
                return ResourceManager.GetString("SAM_SEErrorWrongPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible to connect to SAM-SE using this password.
        /// </summary>
        public static string SAM_SEErrorWrongPwd {
            get {
                return ResourceManager.GetString("SAM_SEErrorWrongPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE function size argument is wrong.
        /// </summary>
        public static string SAM_SEErrorWrongSize {
            get {
                return ResourceManager.GetString("SAM_SEErrorWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM-SE error is unknown : .
        /// </summary>
        public static string SAM_SEUnknownError {
            get {
                return ResourceManager.GetString("SAM_SEUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SI cannot have an odd length.
        /// </summary>
        public static string SiNotValid {
            get {
                return ResourceManager.GetString("SiNotValid", resourceCulture);
            }
        }
    }
}
