//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string CloseCaps {
            get {
                return ResourceManager.GetString("CloseCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy words.
        /// </summary>
        public static string CopyWords {
            get {
                return ResourceManager.GetString("CopyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from seed.
        /// </summary>
        public static string CreateFromSeed {
            get {
                return ResourceManager.GetString("CreateFromSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new key entry.
        /// </summary>
        public static string CreateKeyEntry {
            get {
                return ResourceManager.GetString("CreateKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the key entry.
        /// </summary>
        public static string DeleteKeyEntry {
            get {
                return ResourceManager.GetString("DeleteKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the key entry deletion?.
        /// </summary>
        public static string DeleteKeyEntryConfirmation {
            get {
                return ResourceManager.GetString("DeleteKeyEntryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivate a Key from a Password (using RFC 2898).
        /// </summary>
        public static string DerivatePassword {
            get {
                return ResourceManager.GetString("DerivatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document generated with.
        /// </summary>
        public static string DocumentGenerated {
            get {
                return ResourceManager.GetString("DocumentGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit default key entry definition.
        /// </summary>
        public static string EditDefaultKeyEntry {
            get {
                return ResourceManager.GetString("EditDefaultKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the key entry.
        /// </summary>
        public static string EditKeyEntry {
            get {
                return ResourceManager.GetString("EditKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Store Favorite.
        /// </summary>
        public static string FavoriteHelper {
            get {
                return ResourceManager.GetString("FavoriteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment Export / Print.
        /// </summary>
        public static string FragmentExportPrint {
            get {
                return ResourceManager.GetString("FragmentExportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Fragment #.
        /// </summary>
        public static string FragmentInputHelper {
            get {
                return ResourceManager.GetString("FragmentInputHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Input.
        /// </summary>
        public static string FragmentManualInput {
            get {
                return ResourceManager.GetString("FragmentManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment Value.
        /// </summary>
        public static string FragmentValue {
            get {
                return ResourceManager.GetString("FragmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret value for the key fragment.
        /// </summary>
        public static string FragmentValueHelper {
            get {
                return ResourceManager.GetString("FragmentValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Key Entry.
        /// </summary>
        public static string GenerateKeyEntry {
            get {
                return ResourceManager.GetString("GenerateKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random Key.
        /// </summary>
        public static string GenerateRandom {
            get {
                return ResourceManager.GetString("GenerateRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new words.
        /// </summary>
        public static string GenerateWords {
            get {
                return ResourceManager.GetString("GenerateWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to parent.
        /// </summary>
        public static string GoToParent {
            get {
                return ResourceManager.GetString("GoToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Cryptogram.
        /// </summary>
        public static string ImportCryptogram {
            get {
                return ResourceManager.GetString("ImportCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        public static string ImportFromFile {
            get {
                return ResourceManager.GetString("ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the key entry cryptogram.
        /// </summary>
        public static string ImportKeyEntryCryptogram {
            get {
                return ResourceManager.GetString("ImportKeyEntryCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Now.
        /// </summary>
        public static string ImportNow {
            get {
                return ResourceManager.GetString("ImportNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV.
        /// </summary>
        public static string KCV {
            get {
                return ResourceManager.GetString("KCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV Algorithm.
        /// </summary>
        public static string KCVAlgorithm {
            get {
                return ResourceManager.GetString("KCVAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Checksum algorithm to use.
        /// </summary>
        public static string KCVAlgorithmHelper {
            get {
                return ResourceManager.GetString("KCVAlgorithmHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Checksum Value.
        /// </summary>
        public static string KCVHelper {
            get {
                return ResourceManager.GetString("KCVHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ceremony.
        /// </summary>
        public static string KeyCeremony {
            get {
                return ResourceManager.GetString("KeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragments.
        /// </summary>
        public static string KeyCeremonyFragments {
            get {
                return ResourceManager.GetString("KeyCeremonyFragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of key fragments to use during the ceremony.
        /// </summary>
        public static string KeyCeremonyFragmentsHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyFragmentsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a Key Ceremony to recover or share a key value shared between several individuals..
        /// </summary>
        public static string KeyCeremonyHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KeyCeremonyType {
            get {
                return ResourceManager.GetString("KeyCeremonyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremony Type.
        /// </summary>
        public static string KeyCeremonyTypeHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Ceremony is now ready to be completed..
        /// </summary>
        public static string KeyCeremonyWizardEnd1 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardEnd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the &apos;Finish&apos; button to complete the ceremony..
        /// </summary>
        public static string KeyCeremonyWizardEnd2 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When ready, go to the next step..
        /// </summary>
        public static string KeyCeremonyWizardStart {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather all required individuals.
        /// </summary>
        public static string KeyCeremonyWizardStartReq1 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare all key fragments materials.
        /// </summary>
        public static string KeyCeremonyWizardStartReq2 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the environment match the minimal security requirements.
        /// </summary>
        public static string KeyCeremonyWizardStartReq3 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum.
        /// </summary>
        public static string KeyChecksum {
            get {
                return ResourceManager.GetString("KeyChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Checksum.
        /// </summary>
        public static string KeyChecksumHelper {
            get {
                return ResourceManager.GetString("KeyChecksumHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key has been computed..
        /// </summary>
        public static string KeyComputationConfirmation {
            get {
                return ResourceManager.GetString("KeyComputationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Entry.
        /// </summary>
        public static string KeyEntry {
            get {
                return ResourceManager.GetString("KeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptogram.
        /// </summary>
        public static string KeyEntryCryptogram {
            get {
                return ResourceManager.GetString("KeyEntryCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cryptogram containing the key entry details.
        /// </summary>
        public static string KeyEntryCryptogramHelper {
            get {
                return ResourceManager.GetString("KeyEntryCryptogramHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential information about the Key Entry. Defines its properties and key values..
        /// </summary>
        public static string KeyEntryEditHelper {
            get {
                return ResourceManager.GetString("KeyEntryEditHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string KeyEntryIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Entry Identifier.
        /// </summary>
        public static string KeyEntryIdentifierHelper {
            get {
                return ResourceManager.GetString("KeyEntryIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string KeyEntryLabel {
            get {
                return ResourceManager.GetString("KeyEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label/note about the key entry..
        /// </summary>
        public static string KeyEntryLabelHelper {
            get {
                return ResourceManager.GetString("KeyEntryLabelHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Entry Link.
        /// </summary>
        public static string KeyEntryLink {
            get {
                return ResourceManager.GetString("KeyEntryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the Cryptogram to change the Key Entry, from another Key Store..
        /// </summary>
        public static string KeyEntryLinkHelper {
            get {
                return ResourceManager.GetString("KeyEntryLinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string KeyEntryProperties {
            get {
                return ResourceManager.GetString("KeyEntryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key entry type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string KeyEntryVariant {
            get {
                return ResourceManager.GetString("KeyEntryVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key entry variant.
        /// </summary>
        public static string KeyEntryVariantHelper {
            get {
                return ResourceManager.GetString("KeyEntryVariantHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document is proprietary, sensitive and confidential. It should not be used, published or redistributed without the owner agreement..
        /// </summary>
        public static string KeyExportDisclaimer1 {
            get {
                return ResourceManager.GetString("KeyExportDisclaimer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you received this document by mistake, please destroy it without further notice and directly report this action to a security officer..
        /// </summary>
        public static string KeyExportDisclaimer2 {
            get {
                return ResourceManager.GetString("KeyExportDisclaimer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Export / Print.
        /// </summary>
        public static string KeyExportPrint {
            get {
                return ResourceManager.GetString("KeyExportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Key Generation.
        /// </summary>
        public static string KeyGeneration {
            get {
                return ResourceManager.GetString("KeyGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Link.
        /// </summary>
        public static string KeyLink {
            get {
                return ResourceManager.GetString("KeyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump the key value from another Key Store..
        /// </summary>
        public static string KeyLinkHelper {
            get {
                return ResourceManager.GetString("KeyLinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string KeySize {
            get {
                return ResourceManager.GetString("KeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Size.
        /// </summary>
        public static string KeySizeHelper {
            get {
                return ResourceManager.GetString("KeySizeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Store Properties.
        /// </summary>
        public static string KeyStoreProperties {
            get {
                return ResourceManager.GetString("KeyStoreProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KeyStoreType {
            get {
                return ResourceManager.GetString("KeyStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Store Type.
        /// </summary>
        public static string KeyStoreTypeHelper {
            get {
                return ResourceManager.GetString("KeyStoreTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string KeyTags {
            get {
                return ResourceManager.GetString("KeyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Tags.
        /// </summary>
        public static string KeyTagsHelper {
            get {
                return ResourceManager.GetString("KeyTagsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Value.
        /// </summary>
        public static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret value for the key.
        /// </summary>
        public static string KeyValueHelper {
            get {
                return ResourceManager.GetString("KeyValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Version.
        /// </summary>
        public static string KeyVersionHelper {
            get {
                return ResourceManager.GetString("KeyVersionHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link failed with following error:.
        /// </summary>
        public static string LinkError {
            get {
                return ResourceManager.GetString("LinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to another Key Store.
        /// </summary>
        public static string LinkHelper {
            get {
                return ResourceManager.GetString("LinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link succeeded..
        /// </summary>
        public static string LinkSuccess {
            get {
                return ResourceManager.GetString("LinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        public static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create key from Mnemonic (BIP-39).
        /// </summary>
        public static string MnemonicHelper {
            get {
                return ResourceManager.GetString("MnemonicHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Favorite Key Store.
        /// </summary>
        public static string NewFavorite {
            get {
                return ResourceManager.GetString("NewFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the new folder to create.
        /// </summary>
        public static string NewFolderNameHelper {
            get {
                return ResourceManager.GetString("NewFolderNameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New key entry.
        /// </summary>
        public static string NewKeyEntry {
            get {
                return ResourceManager.GetString("NewKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string PassphraseHelper {
            get {
                return ResourceManager.GetString("PassphraseHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to derivate the key from.
        /// </summary>
        public static string PasswordDivHelper {
            get {
                return ResourceManager.GetString("PasswordDivHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit.
        /// </summary>
        public static string PleaseVisit {
            get {
                return ResourceManager.GetString("PleaseVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to another Key Store.
        /// </summary>
        public static string PublishKeyStore {
            get {
                return ResourceManager.GetString("PublishKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr Code.
        /// </summary>
        public static string QrCode {
            get {
                return ResourceManager.GetString("QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The salt to use for key derivation.
        /// </summary>
        public static string SaltDivHelper {
            get {
                return ResourceManager.GetString("SaltDivHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Terms.
        /// </summary>
        public static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key store secret.
        /// </summary>
        public static string SecretHelper {
            get {
                return ResourceManager.GetString("SecretHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Folder:.
        /// </summary>
        public static string SelectedFolder {
            get {
                return ResourceManager.GetString("SelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Folder.
        /// </summary>
        public static string SelectTargetFolder {
            get {
                return ResourceManager.GetString("SelectTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the sharing ceremony.
        /// </summary>
        public static string StartSharingKeyCeremony {
            get {
                return ResourceManager.GetString("StartSharingKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the reunification ceremony.
        /// </summary>
        public static string StartUnionKeyCeremony {
            get {
                return ResourceManager.GetString("StartUnionKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Unselect all.
        /// </summary>
        public static string ToggleSelectAll {
            get {
                return ResourceManager.GetString("ToggleSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / Hide key entries selection boxes.
        /// </summary>
        public static string ToggleSelection {
            get {
                return ResourceManager.GetString("ToggleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic words.
        /// </summary>
        public static string WordsHelper {
            get {
                return ResourceManager.GetString("WordsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string WordsLanguage {
            get {
                return ResourceManager.GetString("WordsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Language.
        /// </summary>
        public static string WordsLanguageHelper {
            get {
                return ResourceManager.GetString("WordsLanguageHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapping Key.
        /// </summary>
        public static string WrappingKey {
            get {
                return ResourceManager.GetString("WrappingKey", resourceCulture);
            }
        }
    }
}
