//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add div input fragment.
        /// </summary>
        public static string AddDivInputFragment {
            get {
                return ResourceManager.GetString("AddDivInputFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Batch Progress.
        /// </summary>
        public static string BatchProgress {
            get {
                return ResourceManager.GetString("BatchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string ButtonPause {
            get {
                return ResourceManager.GetString("ButtonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume.
        /// </summary>
        public static string ButtonResume {
            get {
                return ResourceManager.GetString("ButtonResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip.
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CLOSE.
        /// </summary>
        public static string CloseCaps {
            get {
                return ResourceManager.GetString("CloseCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm each unit before proceeding.
        /// </summary>
        public static string ConfirmEachUnit {
            get {
                return ResourceManager.GetString("ConfirmEachUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continuous mode.
        /// </summary>
        public static string ContinuousMode {
            get {
                return ResourceManager.GetString("ContinuousMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy to clipboard.
        /// </summary>
        public static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy the Key Entry.
        /// </summary>
        public static string CopyKeyEntry {
            get {
                return ResourceManager.GetString("CopyKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy words.
        /// </summary>
        public static string CopyWords {
            get {
                return ResourceManager.GetString("CopyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create from seed.
        /// </summary>
        public static string CreateFromSeed {
            get {
                return ResourceManager.GetString("CreateFromSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new key entry.
        /// </summary>
        public static string CreateKeyEntry {
            get {
                return ResourceManager.GetString("CreateKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the key entry.
        /// </summary>
        public static string DeleteKeyEntry {
            get {
                return ResourceManager.GetString("DeleteKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you confirm the key entry deletion?.
        /// </summary>
        public static string DeleteKeyEntryConfirmation {
            get {
                return ResourceManager.GetString("DeleteKeyEntryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derivate a Key from a Password (using RFC 2898).
        /// </summary>
        public static string DerivatePassword {
            get {
                return ResourceManager.GetString("DerivatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diff with another Key Store.
        /// </summary>
        public static string DiffKeyStore {
            get {
                return ResourceManager.GetString("DiffKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification Input.
        /// </summary>
        public static string DivInput {
            get {
                return ResourceManager.GetString("DivInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The optional diversification input to derivate the base key with..
        /// </summary>
        public static string DivInputHelper {
            get {
                return ResourceManager.GetString("DivInputHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document generated with.
        /// </summary>
        public static string DocumentGenerated {
            get {
                return ResourceManager.GetString("DocumentGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dry Run (don&apos;t store).
        /// </summary>
        public static string DryRun {
            get {
                return ResourceManager.GetString("DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit default key entry definition.
        /// </summary>
        public static string EditDefaultKeyEntry {
            get {
                return ResourceManager.GetString("EditDefaultKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit the key entry.
        /// </summary>
        public static string EditKeyEntry {
            get {
                return ResourceManager.GetString("EditKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable workflow provisioning.
        /// </summary>
        public static string EnableFlowProvisioning {
            get {
                return ResourceManager.GetString("EnableFlowProvisioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Notifications.
        /// </summary>
        public static string EnableNotifications {
            get {
                return ResourceManager.GetString("EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution Logs.
        /// </summary>
        public static string ExecutionLogs {
            get {
                return ResourceManager.GetString("ExecutionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to file.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Store Favorite.
        /// </summary>
        public static string FavoriteHelper {
            get {
                return ResourceManager.GetString("FavoriteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Workflow.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provision multiple units in a batch with optional confirmations..
        /// </summary>
        public static string FlowDescription {
            get {
                return ResourceManager.GetString("FlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Workflow not supported for this key store.
        /// </summary>
        public static string FlowNotSupported {
            get {
                return ResourceManager.GetString("FlowNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fragment Export / Print.
        /// </summary>
        public static string FragmentExportPrint {
            get {
                return ResourceManager.GetString("FragmentExportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Fragment #.
        /// </summary>
        public static string FragmentInputHelper {
            get {
                return ResourceManager.GetString("FragmentInputHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual Input.
        /// </summary>
        public static string FragmentManualInput {
            get {
                return ResourceManager.GetString("FragmentManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fragment Value.
        /// </summary>
        public static string FragmentValue {
            get {
                return ResourceManager.GetString("FragmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The secret value for the key fragment.
        /// </summary>
        public static string FragmentValueHelper {
            get {
                return ResourceManager.GetString("FragmentValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Key Entries.
        /// </summary>
        public static string GenerateKeyEntries {
            get {
                return ResourceManager.GetString("GenerateKeyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Key Entry.
        /// </summary>
        public static string GenerateKeyEntry {
            get {
                return ResourceManager.GetString("GenerateKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Only if Missing.
        /// </summary>
        public static string GenerateOnlyIfMissing {
            get {
                return ResourceManager.GetString("GenerateOnlyIfMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Random Key.
        /// </summary>
        public static string GenerateRandom {
            get {
                return ResourceManager.GetString("GenerateRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate new words.
        /// </summary>
        public static string GenerateWords {
            get {
                return ResourceManager.GetString("GenerateWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string GenericValue {
            get {
                return ResourceManager.GetString("GenericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to parent.
        /// </summary>
        public static string GoToParent {
            get {
                return ResourceManager.GetString("GoToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Cryptogram.
        /// </summary>
        public static string ImportCryptogram {
            get {
                return ResourceManager.GetString("ImportCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import from file.
        /// </summary>
        public static string ImportFromFile {
            get {
                return ResourceManager.GetString("ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import the key entry cryptogram.
        /// </summary>
        public static string ImportKeyEntryCryptogram {
            get {
                return ResourceManager.GetString("ImportKeyEntryCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Now.
        /// </summary>
        public static string ImportNow {
            get {
                return ResourceManager.GetString("ImportNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KCV.
        /// </summary>
        public static string KCV {
            get {
                return ResourceManager.GetString("KCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KCV Algorithm.
        /// </summary>
        public static string KCVAlgorithm {
            get {
                return ResourceManager.GetString("KCVAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Checksum algorithm to use.
        /// </summary>
        public static string KCVAlgorithmHelper {
            get {
                return ResourceManager.GetString("KCVAlgorithmHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Checksum Value.
        /// </summary>
        public static string KCVHelper {
            get {
                return ResourceManager.GetString("KCVHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Ceremony.
        /// </summary>
        public static string KeyCeremony {
            get {
                return ResourceManager.GetString("KeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fragments.
        /// </summary>
        public static string KeyCeremonyFragments {
            get {
                return ResourceManager.GetString("KeyCeremonyFragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of key fragments to use during the ceremony.
        /// </summary>
        public static string KeyCeremonyFragmentsHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyFragmentsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run a Key Ceremony to recover or share a key value shared between several individuals..
        /// </summary>
        public static string KeyCeremonyHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyCeremonyType {
            get {
                return ResourceManager.GetString("KeyCeremonyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ceremony Type.
        /// </summary>
        public static string KeyCeremonyTypeHelper {
            get {
                return ResourceManager.GetString("KeyCeremonyTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Ceremony is now ready to be completed..
        /// </summary>
        public static string KeyCeremonyWizardEnd1 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardEnd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press the &apos;Finish&apos; button to complete the ceremony..
        /// </summary>
        public static string KeyCeremonyWizardEnd2 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When ready, go to the next step..
        /// </summary>
        public static string KeyCeremonyWizardStart {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gather all required individuals.
        /// </summary>
        public static string KeyCeremonyWizardStartReq1 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prepare all key fragments materials.
        /// </summary>
        public static string KeyCeremonyWizardStartReq2 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ensure the environment match the minimal security requirements.
        /// </summary>
        public static string KeyCeremonyWizardStartReq3 {
            get {
                return ResourceManager.GetString("KeyCeremonyWizardStartReq3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checksum.
        /// </summary>
        public static string KeyChecksum {
            get {
                return ResourceManager.GetString("KeyChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Checksum.
        /// </summary>
        public static string KeyChecksumHelper {
            get {
                return ResourceManager.GetString("KeyChecksumHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key has been computed..
        /// </summary>
        public static string KeyComputationConfirmation {
            get {
                return ResourceManager.GetString("KeyComputationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Entries Export/Print.
        /// </summary>
        public static string KeyEntriesExportPrint {
            get {
                return ResourceManager.GetString("KeyEntriesExportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Entry.
        /// </summary>
        public static string KeyEntry {
            get {
                return ResourceManager.GetString("KeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key entry classes.
        /// </summary>
        public static string KeyEntryClasses {
            get {
                return ResourceManager.GetString("KeyEntryClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptogram.
        /// </summary>
        public static string KeyEntryCryptogram {
            get {
                return ResourceManager.GetString("KeyEntryCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The cryptogram containing the key entry details.
        /// </summary>
        public static string KeyEntryCryptogramHelper {
            get {
                return ResourceManager.GetString("KeyEntryCryptogramHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confidential information about the Key Entry. Defines its properties and key values..
        /// </summary>
        public static string KeyEntryEditHelper {
            get {
                return ResourceManager.GetString("KeyEntryEditHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KeyEntryIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Entry Identifier.
        /// </summary>
        public static string KeyEntryIdentifierHelper {
            get {
                return ResourceManager.GetString("KeyEntryIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label.
        /// </summary>
        public static string KeyEntryLabel {
            get {
                return ResourceManager.GetString("KeyEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label/note about the key entry..
        /// </summary>
        public static string KeyEntryLabelHelper {
            get {
                return ResourceManager.GetString("KeyEntryLabelHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Entry Link.
        /// </summary>
        public static string KeyEntryLink {
            get {
                return ResourceManager.GetString("KeyEntryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compute the Cryptogram to change the Key Entry, from another Key Store..
        /// </summary>
        public static string KeyEntryLinkHelper {
            get {
                return ResourceManager.GetString("KeyEntryLinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        public static string KeyEntryProperties {
            get {
                return ResourceManager.GetString("KeyEntryProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key entry type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variant.
        /// </summary>
        public static string KeyEntryVariant {
            get {
                return ResourceManager.GetString("KeyEntryVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key entry variant.
        /// </summary>
        public static string KeyEntryVariantHelper {
            get {
                return ResourceManager.GetString("KeyEntryVariantHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This document is proprietary, sensitive and confidential. It should not be used, published or redistributed without the owner agreement..
        /// </summary>
        public static string KeyExportDisclaimer1 {
            get {
                return ResourceManager.GetString("KeyExportDisclaimer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you received this document by mistake, please destroy it without further notice and directly report this action to a security officer..
        /// </summary>
        public static string KeyExportDisclaimer2 {
            get {
                return ResourceManager.GetString("KeyExportDisclaimer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Export / Print.
        /// </summary>
        public static string KeyExportPrint {
            get {
                return ResourceManager.GetString("KeyExportPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speech.
        /// </summary>
        public static string KeyExportSpeech {
            get {
                return ResourceManager.GetString("KeyExportSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local Key Generation.
        /// </summary>
        public static string KeyGeneration {
            get {
                return ResourceManager.GetString("KeyGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Link.
        /// </summary>
        public static string KeyLink {
            get {
                return ResourceManager.GetString("KeyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dump the key value from another Key Store..
        /// </summary>
        public static string KeyLinkHelper {
            get {
                return ResourceManager.GetString("KeyLinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔑 .
        /// </summary>
        public static string KeyLogo {
            get {
                return ResourceManager.GetString("KeyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        public static string KeySize {
            get {
                return ResourceManager.GetString("KeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Size (bits).
        /// </summary>
        public static string KeySizeHelper {
            get {
                return ResourceManager.GetString("KeySizeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        public static string KeySizeInBytes {
            get {
                return ResourceManager.GetString("KeySizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Size (bytes).
        /// </summary>
        public static string KeySizeInBytesHelper {
            get {
                return ResourceManager.GetString("KeySizeInBytesHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Store Attribute.
        /// </summary>
        public static string KeyStoreAttribute {
            get {
                return ResourceManager.GetString("KeyStoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current KeyStore Progress.
        /// </summary>
        public static string KeyStoreProgress {
            get {
                return ResourceManager.GetString("KeyStoreProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Store Properties.
        /// </summary>
        public static string KeyStoreProperties {
            get {
                return ResourceManager.GetString("KeyStoreProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyStoreType {
            get {
                return ResourceManager.GetString("KeyStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Store Type.
        /// </summary>
        public static string KeyStoreTypeHelper {
            get {
                return ResourceManager.GetString("KeyStoreTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tags.
        /// </summary>
        public static string KeyTags {
            get {
                return ResourceManager.GetString("KeyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Tags.
        /// </summary>
        public static string KeyTagsHelper {
            get {
                return ResourceManager.GetString("KeyTagsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Value.
        /// </summary>
        public static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The secret value for the key.
        /// </summary>
        public static string KeyValueHelper {
            get {
                return ResourceManager.GetString("KeyValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Version.
        /// </summary>
        public static string KeyVersionHelper {
            get {
                return ResourceManager.GetString("KeyVersionHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The link failed with following error:.
        /// </summary>
        public static string LinkError {
            get {
                return ResourceManager.GetString("LinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link to another Key Store.
        /// </summary>
        public static string LinkHelper {
            get {
                return ResourceManager.GetString("LinkHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The link succeeded..
        /// </summary>
        public static string LinkSuccess {
            get {
                return ResourceManager.GetString("LinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable detailed logs per unit.
        /// </summary>
        public static string LoggingVerbosity {
            get {
                return ResourceManager.GetString("LoggingVerbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max units in workflow.
        /// </summary>
        public static string MaxUnits {
            get {
                return ResourceManager.GetString("MaxUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the number of units to provision..
        /// </summary>
        public static string MaxUnitsHelper {
            get {
                return ResourceManager.GetString("MaxUnitsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of units to provision.
        /// </summary>
        public static string MaxUnitsHelperShort {
            get {
                return ResourceManager.GetString("MaxUnitsHelperShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mnemonic.
        /// </summary>
        public static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create key from Mnemonic (BIP-39).
        /// </summary>
        public static string MnemonicHelper {
            get {
                return ResourceManager.GetString("MnemonicHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Favorite Key Store.
        /// </summary>
        public static string NewFavorite {
            get {
                return ResourceManager.GetString("NewFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New folder.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the new folder to create.
        /// </summary>
        public static string NewFolderNameHelper {
            get {
                return ResourceManager.GetString("NewFolderNameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New key entry.
        /// </summary>
        public static string NewKeyEntry {
            get {
                return ResourceManager.GetString("NewKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notify on successful unit provisioning.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order by Id.
        /// </summary>
        public static string OrderById {
            get {
                return ResourceManager.GetString("OrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order by Label.
        /// </summary>
        public static string OrderByLabel {
            get {
                return ResourceManager.GetString("OrderByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordering.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Byte.
        /// </summary>
        public static string PadByte {
            get {
                return ResourceManager.GetString("PadByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Padding Length.
        /// </summary>
        public static string PadLength {
            get {
                return ResourceManager.GetString("PadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passphrase.
        /// </summary>
        public static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passphrase.
        /// </summary>
        public static string PassphraseHelper {
            get {
                return ResourceManager.GetString("PassphraseHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password to derivate the key from.
        /// </summary>
        public static string PasswordDivHelper {
            get {
                return ResourceManager.GetString("PasswordDivHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please visit.
        /// </summary>
        public static string PleaseVisit {
            get {
                return ResourceManager.GetString("PleaseVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View as Printable List.
        /// </summary>
        public static string PrintSelection {
            get {
                return ResourceManager.GetString("PrintSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publish to another Key Store.
        /// </summary>
        public static string PublishKeyStore {
            get {
                return ResourceManager.GetString("PublishKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publish as batch ({0} unit{1}) to : {2}.
        /// </summary>
        public static string PublishLabel {
            get {
                return ResourceManager.GetString("PublishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable.
        /// </summary>
        public static string PublishVariable {
            get {
                return ResourceManager.GetString("PublishVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A variable which can be used during publish (using %{pubvar})..
        /// </summary>
        public static string PublishVariableHelper {
            get {
                return ResourceManager.GetString("PublishVariableHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qr Code.
        /// </summary>
        public static string QrCode {
            get {
                return ResourceManager.GetString("QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random Number Generator.
        /// </summary>
        public static string RandomGenerator {
            get {
                return ResourceManager.GetString("RandomGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random Length.
        /// </summary>
        public static string RandomLength {
            get {
                return ResourceManager.GetString("RandomLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolve Key links.
        /// </summary>
        public static string ResolveKeyLinks {
            get {
                return ResourceManager.GetString("ResolveKeyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolve Variables.
        /// </summary>
        public static string ResolveVariables {
            get {
                return ResourceManager.GetString("ResolveVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry failed units.
        /// </summary>
        public static string RetryOnFailure {
            get {
                return ResourceManager.GetString("RetryOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry On Failure.
        /// </summary>
        public static string RetryOnFailureBatch {
            get {
                return ResourceManager.GetString("RetryOnFailureBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salt.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The salt to use for key derivation.
        /// </summary>
        public static string SaltDivHelper {
            get {
                return ResourceManager.GetString("SaltDivHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Terms.
        /// </summary>
        public static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key store secret.
        /// </summary>
        public static string SecretHelper {
            get {
                return ResourceManager.GetString("SecretHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected Folder:.
        /// </summary>
        public static string SelectedFolder {
            get {
                return ResourceManager.GetString("SelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Target Folder.
        /// </summary>
        public static string SelectTargetFolder {
            get {
                return ResourceManager.GetString("SelectTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the sharing ceremony.
        /// </summary>
        public static string StartSharingKeyCeremony {
            get {
                return ResourceManager.GetString("StartSharingKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the reunification ceremony.
        /// </summary>
        public static string StartUnionKeyCeremony {
            get {
                return ResourceManager.GetString("StartUnionKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Static Value.
        /// </summary>
        public static string StaticValue {
            get {
                return ResourceManager.GetString("StaticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processing : .
        /// </summary>
        public static string TextProcessing {
            get {
                return ResourceManager.GetString("TextProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set a maximum wait time before failing.
        /// </summary>
        public static string TimeoutWait {
            get {
                return ResourceManager.GetString("TimeoutWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout Wait.
        /// </summary>
        public static string TimeoutWaitBatch {
            get {
                return ResourceManager.GetString("TimeoutWaitBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seconds.
        /// </summary>
        public static string TimeSecond {
            get {
                return ResourceManager.GetString("TimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select/Unselect all.
        /// </summary>
        public static string ToggleSelectAll {
            get {
                return ResourceManager.GetString("ToggleSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show / Hide key entries selection boxes.
        /// </summary>
        public static string ToggleSelection {
            get {
                return ResourceManager.GetString("ToggleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add visible elements to current selection.
        /// </summary>
        public static string ToggleSelectVisible {
            get {
                return ResourceManager.GetString("ToggleSelectVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verbose Logging.
        /// </summary>
        public static string VerboseLogging {
            get {
                return ResourceManager.GetString("VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wizard.
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mnemonic words.
        /// </summary>
        public static string WordsHelper {
            get {
                return ResourceManager.GetString("WordsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string WordsLanguage {
            get {
                return ResourceManager.GetString("WordsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Words Language.
        /// </summary>
        public static string WordsLanguageHelper {
            get {
                return ResourceManager.GetString("WordsLanguageHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrapping Key.
        /// </summary>
        public static string WrappingKey {
            get {
                return ResourceManager.GetString("WrappingKey", resourceCulture);
            }
        }
    }
}
