//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.NXP_SAM.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.NXP_SAM.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM for Access Control.
        /// </summary>
        public static string AccessControlWizard {
            get {
                return ResourceManager.GetString("AccessControlWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define SAM key entries following recommended guidelines for a SAM used by Access Control systems..
        /// </summary>
        public static string AccessControlWizardDescription {
            get {
                return ResourceManager.GetString("AccessControlWizardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Mifare SAM features.
        /// </summary>
        public static string ActivateMifareSAM {
            get {
                return ResourceManager.GetString("ActivateMifareSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow dump SecretKey.
        /// </summary>
        public static string AllowDumpSecretKey {
            get {
                return ResourceManager.GetString("AllowDumpSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow dump SecretKey with div.
        /// </summary>
        public static string AllowDumpSecretKeyWithDiv {
            get {
                return ResourceManager.GetString("AllowDumpSecretKeyWithDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate Host.
        /// </summary>
        public static string AuthenticateHost {
            get {
                return ResourceManager.GetString("AuthenticateHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate Key.
        /// </summary>
        public static string AuthenticateKey {
            get {
                return ResourceManager.GetString("AuthenticateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Mode.
        /// </summary>
        public static string AuthenticationMode {
            get {
                return ResourceManager.GetString("AuthenticationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SAM authentication mode.
        /// </summary>
        public static string AuthenticationModeHelper {
            get {
                return ResourceManager.GetString("AuthenticationModeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically switch the SAM to AV2 mode if required when performing updates.
        /// </summary>
        public static string AutoSwitchToAV2 {
            get {
                return ResourceManager.GetString("AutoSwitchToAV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Key Reference.
        /// </summary>
        public static string ChangeKeyReference {
            get {
                return ResourceManager.GetString("ChangeKeyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto based on SecretKey.
        /// </summary>
        public static string CryptoBasedSecretKey {
            get {
                return ResourceManager.GetString("CryptoBasedSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire.
        /// </summary>
        public static string DESFire {
            get {
                return ResourceManager.GetString("DESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AID.
        /// </summary>
        public static string DESFireAID {
            get {
                return ResourceManager.GetString("DESFireAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DESFire Application Identifier.
        /// </summary>
        public static string DESFireAIDHelper {
            get {
                return ResourceManager.GetString("DESFireAIDHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESFire Authentication.
        /// </summary>
        public static string DESFireAuthenticate {
            get {
                return ResourceManager.GetString("DESFireAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File No.
        /// </summary>
        public static string DESFireFileNo {
            get {
                return ResourceManager.GetString("DESFireFileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DESFire File number.
        /// </summary>
        public static string DESFireFileNoHelper {
            get {
                return ResourceManager.GetString("DESFireFileNoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Number.
        /// </summary>
        public static string DESFireKeyNumber {
            get {
                return ResourceManager.GetString("DESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DESFire Key Number.
        /// </summary>
        public static string DESFireKeyNumberHelper {
            get {
                return ResourceManager.GetString("DESFireKeyNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Change Key PICC.
        /// </summary>
        public static string DisableChangeKeyPICC {
            get {
                return ResourceManager.GetString("DisableChangeKeyPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Decrypt Data.
        /// </summary>
        public static string DisableDecryptData {
            get {
                return ResourceManager.GetString("DisableDecryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Encrypt Data.
        /// </summary>
        public static string DisableEncryptData {
            get {
                return ResourceManager.GetString("DisableEncryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Generate MAC From PICC.
        /// </summary>
        public static string DisableGenerateMACFromPICC {
            get {
                return ResourceManager.GetString("DisableGenerateMACFromPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Key Entry.
        /// </summary>
        public static string DisableKeyEntry {
            get {
                return ResourceManager.GetString("DisableKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Verify MAC From PICC.
        /// </summary>
        public static string DisableVerifyMACFromPICC {
            get {
                return ResourceManager.GetString("DisableVerifyMACFromPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Input.
        /// </summary>
        public static string DivInput {
            get {
                return ResourceManager.GetString("DivInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversification Input to use for the key diversification (optional).
        /// </summary>
        public static string DivInputHelper {
            get {
                return ResourceManager.GetString("DivInputHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the key usage counter.
        /// </summary>
        public static string EditKUC {
            get {
                return ResourceManager.GetString("EditKUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dump SessionKey.
        /// </summary>
        public static string EnableDumpSessionKey {
            get {
                return ResourceManager.GetString("EnableDumpSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Key.
        /// </summary>
        public static string EncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Encryption Key for SAM Manager Template.
        /// </summary>
        public static string EncryptionKeyHelper {
            get {
                return ResourceManager.GetString("EncryptionKeyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force the SAM version.
        /// </summary>
        public static string ForceCardType {
            get {
                return ResourceManager.GetString("ForceCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default the software will automatically detect the SAM type/version. Such automatic detection can be overriden..
        /// </summary>
        public static string ForceCardTypeHelper {
            get {
                return ResourceManager.GetString("ForceCardTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new SAM Master Key.
        /// </summary>
        public static string GenerateSAMMasterKey {
            get {
                return ResourceManager.GetString("GenerateSAMMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new SAM Unlock Key.
        /// </summary>
        public static string GenerateSAMUnlockKey {
            get {
                return ResourceManager.GetString("GenerateSAMUnlockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SAM Version.
        /// </summary>
        public static string GetSAMVersion {
            get {
                return ResourceManager.GetString("GetSAMVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template File.
        /// </summary>
        public static string ISLOGTemplateFile {
            get {
                return ResourceManager.GetString("ISLOGTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Template File created with ISLOG SAM Manager.
        /// </summary>
        public static string ISLOGTemplateFileHelper {
            get {
                return ResourceManager.GetString("ISLOGTemplateFileHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep IV.
        /// </summary>
        public static string KeepIV {
            get {
                return ResourceManager.GetString("KeepIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Diversification.
        /// </summary>
        public static string KeyDiversification {
            get {
                return ResourceManager.GetString("KeyDiversification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Entry.
        /// </summary>
        public static string KeyEntry {
            get {
                return ResourceManager.GetString("KeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string KeyEntryIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Entry Identifier.
        /// </summary>
        public static string KeyEntryIdentifierHelper {
            get {
                return ResourceManager.GetString("KeyEntryIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM Key Entry Type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Type.
        /// </summary>
        public static string KeyType {
            get {
                return ResourceManager.GetString("KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SAM Key Type.
        /// </summary>
        public static string KeyTypeHelper {
            get {
                return ResourceManager.GetString("KeyTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Value.
        /// </summary>
        public static string KeyValueHelper {
            get {
                return ResourceManager.GetString("KeyValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Version.
        /// </summary>
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Version.
        /// </summary>
        public static string KeyVersionHelper {
            get {
                return ResourceManager.GetString("KeyVersionHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Usage Counter.
        /// </summary>
        public static string KUC {
            get {
                return ResourceManager.GetString("KUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string KUCIdentifier {
            get {
                return ResourceManager.GetString("KUCIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string KUCIdentifierHelper {
            get {
                return ResourceManager.GetString("KUCIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string KUCLimit {
            get {
                return ResourceManager.GetString("KUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Counter Limit.
        /// </summary>
        public static string KUCLimitHelper {
            get {
                return ResourceManager.GetString("KUCLimitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter #.
        /// </summary>
        public static string KUCReference {
            get {
                return ResourceManager.GetString("KUCReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Usage Counter reference.
        /// </summary>
        public static string KUCReferenceHelper {
            get {
                return ResourceManager.GetString("KUCReferenceHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string KUCValue {
            get {
                return ResourceManager.GetString("KUCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Counter Current Value.
        /// </summary>
        public static string KUCValueHelper {
            get {
                return ResourceManager.GetString("KUCValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock / Unlock.
        /// </summary>
        public static string LockUnlock {
            get {
                return ResourceManager.GetString("LockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string LockUnlockAction {
            get {
                return ResourceManager.GetString("LockUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC Key.
        /// </summary>
        public static string PICCKey {
            get {
                return ResourceManager.GetString("PICCKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Provider.
        /// </summary>
        public static string ReaderProvider {
            get {
                return ResourceManager.GetString("ReaderProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Provider.
        /// </summary>
        public static string ReaderProviderHelper {
            get {
                return ResourceManager.GetString("ReaderProviderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Unit.
        /// </summary>
        public static string ReaderUnit {
            get {
                return ResourceManager.GetString("ReaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Unit.
        /// </summary>
        public static string ReaderUnitHelper {
            get {
                return ResourceManager.GetString("ReaderUnitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read file data.
        /// </summary>
        public static string ReadFile {
            get {
                return ResourceManager.GetString("ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Reader Units.
        /// </summary>
        public static string RefreshReaderUnits {
            get {
                return ResourceManager.GetString("RefreshReaderUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for Offline Perso.
        /// </summary>
        public static string ReservedForPerso {
            get {
                return ResourceManager.GetString("ReservedForPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM Authentication.
        /// </summary>
        public static string SAMAuthentication {
            get {
                return ResourceManager.GetString("SAMAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM AV1.
        /// </summary>
        public static string SAMAV1 {
            get {
                return ResourceManager.GetString("SAMAV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock/Unlock.
        /// </summary>
        public static string SAMLockUnlock {
            get {
                return ResourceManager.GetString("SAMLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM Versions.
        /// </summary>
        public static string SAMVersions {
            get {
                return ResourceManager.GetString("SAMVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StoreSecret {
            get {
                return ResourceManager.GetString("StoreSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the SAM from AV1 to AV2 mode.
        /// </summary>
        public static string SwitchToAV2 {
            get {
                return ResourceManager.GetString("SwitchToAV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Key.
        /// </summary>
        public static string UnlockKey {
            get {
                return ResourceManager.GetString("UnlockKey", resourceCulture);
            }
        }
    }
}
