//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.KeyManager.Library.KeyStore.NXP_SAM.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.KeyManager.Library.KeyStore.NXP_SAM.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM for Access Control.
        /// </summary>
        public static string AccessControlWizard {
            get {
                return ResourceManager.GetString("AccessControlWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define SAM key entries following recommended guidelines for a SAM used by Access Control systems..
        /// </summary>
        public static string AccessControlWizardDescription {
            get {
                return ResourceManager.GetString("AccessControlWizardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate Mifare SAM features.
        /// </summary>
        public static string ActivateMifareSAM {
            get {
                return ResourceManager.GetString("ActivateMifareSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow dump SecretKey.
        /// </summary>
        public static string AllowDumpSecretKey {
            get {
                return ResourceManager.GetString("AllowDumpSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow dump SecretKey with div.
        /// </summary>
        public static string AllowDumpSecretKeyWithDiv {
            get {
                return ResourceManager.GetString("AllowDumpSecretKeyWithDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow Encipher Key Entries.
        /// </summary>
        public static string AllowEncipherKeyEntries {
            get {
                return ResourceManager.GetString("AllowEncipherKeyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow Private Key Export.
        /// </summary>
        public static string AllowPrivateKeyExport {
            get {
                return ResourceManager.GetString("AllowPrivateKeyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticate Host.
        /// </summary>
        public static string AuthenticateHost {
            get {
                return ResourceManager.GetString("AuthenticateHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authenticate Key.
        /// </summary>
        public static string AuthenticateKey {
            get {
                return ResourceManager.GetString("AuthenticateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication Mode.
        /// </summary>
        public static string AuthenticationMode {
            get {
                return ResourceManager.GetString("AuthenticationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SAM authentication mode.
        /// </summary>
        public static string AuthenticationModeHelper {
            get {
                return ResourceManager.GetString("AuthenticationModeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically switch the SAM to AV2 mode if required when performing updates.
        /// </summary>
        public static string AutoSwitchToAV2 {
            get {
                return ResourceManager.GetString("AutoSwitchToAV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Key Reference.
        /// </summary>
        public static string ChangeKeyReference {
            get {
                return ResourceManager.GetString("ChangeKeyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crypto based on SecretKey.
        /// </summary>
        public static string CryptoBasedSecretKey {
            get {
                return ResourceManager.GetString("CryptoBasedSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire.
        /// </summary>
        public static string DESFire {
            get {
                return ResourceManager.GetString("DESFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AID.
        /// </summary>
        public static string DESFireAID {
            get {
                return ResourceManager.GetString("DESFireAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The DESFire Application Identifier.
        /// </summary>
        public static string DESFireAIDHelper {
            get {
                return ResourceManager.GetString("DESFireAIDHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESFire Authentication.
        /// </summary>
        public static string DESFireAuthenticate {
            get {
                return ResourceManager.GetString("DESFireAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File No.
        /// </summary>
        public static string DESFireFileNo {
            get {
                return ResourceManager.GetString("DESFireFileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The DESFire File number.
        /// </summary>
        public static string DESFireFileNoHelper {
            get {
                return ResourceManager.GetString("DESFireFileNoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Number.
        /// </summary>
        public static string DESFireKeyNumber {
            get {
                return ResourceManager.GetString("DESFireKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The DESFire Key Number.
        /// </summary>
        public static string DESFireKeyNumberHelper {
            get {
                return ResourceManager.GetString("DESFireKeyNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Change Key PICC.
        /// </summary>
        public static string DisableChangeKeyPICC {
            get {
                return ResourceManager.GetString("DisableChangeKeyPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Decrypt Data.
        /// </summary>
        public static string DisableDecryptData {
            get {
                return ResourceManager.GetString("DisableDecryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Encrypt Data.
        /// </summary>
        public static string DisableEncryptData {
            get {
                return ResourceManager.GetString("DisableEncryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Generate MAC From PICC.
        /// </summary>
        public static string DisableGenerateMACFromPICC {
            get {
                return ResourceManager.GetString("DisableGenerateMACFromPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Key Entry.
        /// </summary>
        public static string DisableKeyEntry {
            get {
                return ResourceManager.GetString("DisableKeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Sign Data.
        /// </summary>
        public static string DisableSignData {
            get {
                return ResourceManager.GetString("DisableSignData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Verify MAC From PICC.
        /// </summary>
        public static string DisableVerifyMACFromPICC {
            get {
                return ResourceManager.GetString("DisableVerifyMACFromPICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Div Input.
        /// </summary>
        public static string DivInput {
            get {
                return ResourceManager.GetString("DivInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diversification Input to use for the key diversification (optional).
        /// </summary>
        public static string DivInputHelper {
            get {
                return ResourceManager.GetString("DivInputHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit the key usage counter.
        /// </summary>
        public static string EditKUC {
            get {
                return ResourceManager.GetString("EditKUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Dump SessionKey.
        /// </summary>
        public static string EnableDumpSessionKey {
            get {
                return ResourceManager.GetString("EnableDumpSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption Key.
        /// </summary>
        public static string EncryptionKey {
            get {
                return ResourceManager.GetString("EncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master Encryption Key for SAM Manager Template.
        /// </summary>
        public static string EncryptionKeyHelper {
            get {
                return ResourceManager.GetString("EncryptionKeyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force the SAM version.
        /// </summary>
        public static string ForceCardType {
            get {
                return ResourceManager.GetString("ForceCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By default the software will automatically detect the SAM type/version. Such automatic detection can be overriden..
        /// </summary>
        public static string ForceCardTypeHelper {
            get {
                return ResourceManager.GetString("ForceCardTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force Host Internal Change.
        /// </summary>
        public static string ForceHostInternalChange {
            get {
                return ResourceManager.GetString("ForceHostInternalChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Force Host Internal Usage.
        /// </summary>
        public static string ForceHostInternalUsage {
            get {
                return ResourceManager.GetString("ForceHostInternalUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate new SAM Master Key.
        /// </summary>
        public static string GenerateSAMMasterKey {
            get {
                return ResourceManager.GetString("GenerateSAMMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate new SAM Unlock Key.
        /// </summary>
        public static string GenerateSAMUnlockKey {
            get {
                return ResourceManager.GetString("GenerateSAMUnlockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show SAM Version.
        /// </summary>
        public static string GetSAMVersion {
            get {
                return ResourceManager.GetString("GetSAMVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Template File.
        /// </summary>
        public static string ISLOGTemplateFile {
            get {
                return ResourceManager.GetString("ISLOGTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML Template File created with ISLOG SAM Manager.
        /// </summary>
        public static string ISLOGTemplateFileHelper {
            get {
                return ResourceManager.GetString("ISLOGTemplateFileHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep IV.
        /// </summary>
        public static string KeepIV {
            get {
                return ResourceManager.GetString("KeepIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Diversification.
        /// </summary>
        public static string KeyDiversification {
            get {
                return ResourceManager.GetString("KeyDiversification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Entry.
        /// </summary>
        public static string KeyEntry {
            get {
                return ResourceManager.GetString("KeyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KeyEntryIdentifier {
            get {
                return ResourceManager.GetString("KeyEntryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Entry Identifier.
        /// </summary>
        public static string KeyEntryIdentifierHelper {
            get {
                return ResourceManager.GetString("KeyEntryIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string KeyEntryType {
            get {
                return ResourceManager.GetString("KeyEntryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM Key Entry Type.
        /// </summary>
        public static string KeyEntryTypeHelper {
            get {
                return ResourceManager.GetString("KeyEntryTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Type.
        /// </summary>
        public static string KeyType {
            get {
                return ResourceManager.GetString("KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SAM Key Type.
        /// </summary>
        public static string KeyTypeHelper {
            get {
                return ResourceManager.GetString("KeyTypeHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Value.
        /// </summary>
        public static string KeyValueHelper {
            get {
                return ResourceManager.GetString("KeyValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Version.
        /// </summary>
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Version.
        /// </summary>
        public static string KeyVersionHelper {
            get {
                return ResourceManager.GetString("KeyVersionHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Usage Counter.
        /// </summary>
        public static string KUC {
            get {
                return ResourceManager.GetString("KUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KUCIdentifier {
            get {
                return ResourceManager.GetString("KUCIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier.
        /// </summary>
        public static string KUCIdentifierHelper {
            get {
                return ResourceManager.GetString("KUCIdentifierHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Limit.
        /// </summary>
        public static string KUCLimit {
            get {
                return ResourceManager.GetString("KUCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Counter Limit.
        /// </summary>
        public static string KUCLimitHelper {
            get {
                return ResourceManager.GetString("KUCLimitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Counter #.
        /// </summary>
        public static string KUCReference {
            get {
                return ResourceManager.GetString("KUCReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Key Usage Counter reference.
        /// </summary>
        public static string KUCReferenceHelper {
            get {
                return ResourceManager.GetString("KUCReferenceHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string KUCValue {
            get {
                return ResourceManager.GetString("KUCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Counter Current Value.
        /// </summary>
        public static string KUCValueHelper {
            get {
                return ResourceManager.GetString("KUCValueHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock / Unlock.
        /// </summary>
        public static string LockUnlock {
            get {
                return ResourceManager.GetString("LockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string LockUnlockAction {
            get {
                return ResourceManager.GetString("LockUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PICC Key.
        /// </summary>
        public static string PICCKey {
            get {
                return ResourceManager.GetString("PICCKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader Provider.
        /// </summary>
        public static string ReaderProvider {
            get {
                return ResourceManager.GetString("ReaderProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader Provider.
        /// </summary>
        public static string ReaderProviderHelper {
            get {
                return ResourceManager.GetString("ReaderProviderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader Unit.
        /// </summary>
        public static string ReaderUnit {
            get {
                return ResourceManager.GetString("ReaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reader Unit.
        /// </summary>
        public static string ReaderUnitHelper {
            get {
                return ResourceManager.GetString("ReaderUnitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read file data.
        /// </summary>
        public static string ReadFile {
            get {
                return ResourceManager.GetString("ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh Reader Units.
        /// </summary>
        public static string RefreshReaderUnits {
            get {
                return ResourceManager.GetString("RefreshReaderUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reserved for Offline Perso.
        /// </summary>
        public static string ReservedForPerso {
            get {
                return ResourceManager.GetString("ReservedForPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM Authentication.
        /// </summary>
        public static string SAMAuthentication {
            get {
                return ResourceManager.GetString("SAMAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM AV1.
        /// </summary>
        public static string SAMAV1 {
            get {
                return ResourceManager.GetString("SAMAV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock/Unlock.
        /// </summary>
        public static string SAMLockUnlock {
            get {
                return ResourceManager.GetString("SAMLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM Versions.
        /// </summary>
        public static string SAMVersions {
            get {
                return ResourceManager.GetString("SAMVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string StoreSecret {
            get {
                return ResourceManager.GetString("StoreSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch the SAM from AV1 to AV2 mode.
        /// </summary>
        public static string SwitchToAV2 {
            get {
                return ResourceManager.GetString("SwitchToAV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unlock Key.
        /// </summary>
        public static string UnlockKey {
            get {
                return ResourceManager.GetString("UnlockKey", resourceCulture);
            }
        }
    }
}
